[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["Jerry Wang"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.62"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.5", features = ["api-all", "system-tray", "devtools"] }
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
dirs = "5.0"
serde_derive = "1.0.190"
libc = "0.2.152"
auto-launch = "0.5.0"
rev_buf_reader = "0.3.0"
actix-web = "4"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
