[package]
name = "app"
version = "0.2.0-0"
description = "A Tauri App"
authors = [ "Jerry Wang" ]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.62"

[build-dependencies.tauri-build]
version = "1.0.3"
features = [ ]

[dependencies]
serde_json = "1.0"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
dirs = "4.0"
serde_derive = "1.0.138"
libc = "0.2.126"

  [dependencies.serde]
  version = "1.0"
  features = [ "derive" ]

  [dependencies.tauri]
  version = "1.0.3"
  features = [ "api-all", "system-tray" ]

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
