// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    E2flyConfCard: typeof import('./src/components/E2flyConfCard.vue')['default']
    E2flyConfig: typeof import('./src/components/E2flyConfig.vue')['default']
    ICarbonCircleFilled: typeof import('~icons/carbon/circle-filled')['default']
    ICarbonCode: typeof import('~icons/carbon/code')['default']
    ICarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    KButton: typeof import('@0x-jerry/vue-kit')['KButton']
    KCheckbox: typeof import('@0x-jerry/vue-kit')['KCheckbox']
    KCol: typeof import('@0x-jerry/vue-kit')['KCol']
    KDrawer: typeof import('@0x-jerry/vue-kit')['KDrawer']
    KInput: typeof import('@0x-jerry/vue-kit')['KInput']
    KRow: typeof import('@0x-jerry/vue-kit')['KRow']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
