/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BinaryCheckbox: typeof import('./../src/components/BinaryCheckbox.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ICarbonCircleDash: typeof import('~icons/carbon/circle-dash')['default']
    ICarbonCircleFilled: typeof import('~icons/carbon/circle-filled')['default']
    ICarbonCode: typeof import('~icons/carbon/code')['default']
    ICarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loading: typeof import('../src/components/LoadingPanel.vue')['default']
    LoadingPanel: typeof import('./../src/components/LoadingPanel.vue')['default']
    MonacoEditor: typeof import('./../src/components/Editor/MonacoEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
  }
}
