/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICarbonCircleFilled: typeof import('~icons/carbon/circle-filled')['default']
    ICarbonCode: typeof import('~icons/carbon/code')['default']
    ICarbonCopy: typeof import('~icons/carbon/copy')['default']
    ICarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    LoadingPanel: typeof import('./../src/components/LoadingPanel.vue')['default']
    MonacoEditor: typeof import('./../src/components/Editor/MonacoEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
  }
}
