// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    E2flyConfCard: typeof import('./components/E2flyConfCard.vue')['default']
    E2flyConfig: typeof import('./components/E2flyConfig.vue')['default']
    KButton: typeof import('@0x-jerry/vue-kit')['KButton']
    KCol: typeof import('@0x-jerry/vue-kit')['KCol']
    KInput: typeof import('@0x-jerry/vue-kit')['KInput']
    KRow: typeof import('@0x-jerry/vue-kit')['KRow']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
