name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        # Only support macos for now.
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npm.taobao.org
          cache: 'pnpm'

      - name: Install Changelog Tool
        run: npm install -g conventional-changelog-cli

      - name: Generate Release Note
        run: conventional-changelog -p angular -i RELEASE-NOTE.md -s -r 2

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE-NOTE.md
          files: |
            out/*.dmg
